#!/bin/bash
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# Sanitizar (remoção de escapes)
readonly input="${1//$'\r'/}" 

IFS=":" read -r name version <<< "$input"

readonly avaliable=(< $SCRIPT_DIR/avaliable/${name})
# Verificar se o name corresponde a um runtime jṕa disponível pela aplicação
# readonly path_name="${HOME}/.cliverman/runtimes/${name}"
if [[ ! avaliable ]]; then
  echo -e "\033[33m Runtime [${name}] não instalado ou desconhecido.\033[0m"
  echo -e "  Nada foi alterado."
  exit 1
fi

$SCRIPT_DIR/runtimes/${name}/install.sh ${name} ${version}
